# Generated by Django 4.0.1 on 2022-04-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searchhistory',
            fields=[
                ('accountid', models.IntegerField(primary_key=True, serialize=False)),
                ('trackingnum', models.IntegerField()),
            ],
            options={
                'db_table': 'searchhistory',
            },
        ),
    ]
