# Generated by Django 4.0.1 on 2022-04-21 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ups', '0002_searchhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'managed': False},
        ),
    ]
