# Generated by Django 4.0.1 on 2022-04-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truckid', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('idle', 'The truck is idle'), ('traveling', 'The truck is traveling for picking up packages'), ('arrive_warehouse', 'The truck arrived at warehouse'), ('loading', 'The truck is loading packages'), ('delivering', 'The truck is delivering ')], default='idle', max_length=20)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'db_table': 'trucks',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('packageid', models.AutoField(primary_key=True, serialize=False)),
                ('destx', models.IntegerField(blank=True, null=True)),
                ('desty', models.IntegerField(blank=True, null=True)),
                ('warehouseid', models.IntegerField()),
                ('status', models.CharField(choices=[('delivered', 'The packaged has been delivered'), ('delivering', 'The package is under delivering'), ('wait_for_loading', 'The package is waiting for loading'), ('wait_for_pickup', 'The package is waiting for pickup')], default='wait_for_pickup', max_length=20)),
                ('accountid', models.ForeignKey(blank=True, db_column='accountid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ups.account')),
                ('truckid', models.ForeignKey(blank=True, db_column='truckid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ups.truck')),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('amount', models.IntegerField()),
                ('packageid', models.ForeignKey(db_column='packageid', on_delete=django.db.models.deletion.DO_NOTHING, to='ups.package')),
            ],
            options={
                'db_table': 'items',
            },
        ),
    ]
